[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["qamaz <solgrini@yandex.ru>"]
readme = "README.md"
packages = [{include = "hexlet_code"}]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.1.1"
gunicorn = "^20.1.0"
python-dotenv = "^0.21.0"
whitenoise = "^6.2.0"
dj-database-url = "^1.0.0"
django-bootstrap4 = "^22.2"
django-extensions = "^3.2.1"
psycopg2-binary = "^2.9.4"


[tool.poetry.group.dev.dependencies]
ipython = "^8.5.0"
black = "^22.8.0"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
