# Generated by Django 4.1.1 on 2022-10-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
    ]
