# Generated by Django 4.1.2 on 2022-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
