# Generated by Django 4.1.1 on 2022-10-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
