# Generated by Django 4.1.1 on 2022-10-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0003_alter_status_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=30, unique=True, verbose_name="Name"),
        ),
    ]
